### ISSUE TITLE
Answerquest installation: OSError

### ISSUE THREAD

**Issue by mmcs-work** [roemmele/answerquest#2]
I am using `Ubuntu 9.3.0-17ubuntu1~20.04, python 3.8.10`. I have used the provided repository link in a conda environment. (conda environment is updated with this library dependency). There was no conflict with dependencies. `conda` could successfully resolve all the dependencies provided. Installation was successful. 

In python3 CLI, when I wrote the import statement, I got an error:

```
>>> from answerquest import QnAPipeline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user01/miniconda3/envs/myenv/lib/python3.8/site-packages/answerquest/__init__.py", line 1, in <module>
    from .pipeline import QnAPipeline, QA
  File "/home/user01/miniconda3/envs/myenv/lib/python3.8/site-packages/answerquest/pipeline.py", line 11, in <module>
    from onmt.bin.translate import translate, _get_parser
  File "/home/user01/miniconda3/envs/myenv/lib/python3.8/site-packages/onmt/__init__.py", line 4, in <module>
    import onmt.inputters
  File "/home/user01/miniconda3/envs/myenv/lib/python3.8/site-packages/onmt/inputters/__init__.py", line 6, in <module>
    from onmt.inputters.inputter import \
  File "/home/user01/miniconda3/envs/myenv/lib/python3.8/site-packages/onmt/inputters/inputter.py", line 18, in <module>
    from onmt.inputters.audio_dataset import audio_fields
  File "/home/user01/miniconda3/envs/myenv/lib/python3.8/site-packages/onmt/inputters/audio_dataset.py", line 12, in <module>
    import torchaudio
  File "/home/user01/miniconda3/envs/myenv/lib/python3.8/site-packages/torchaudio/__init__.py", line 1, in <module>
    from . import extension  # noqa: F401
  File "/home/user01/miniconda3/envs/myenv/lib/python3.8/site-packages/torchaudio/extension/__init__.py", line 5, in <module>
    _init_extension()
  File "/home/user01/miniconda3/envs/myenv/lib/python3.8/site-packages/torchaudio/extension/extension.py", line 11, in _init_extension
    _init_script_module(ext)
  File "/home/user01/miniconda3/envs/myenv/lib/python3.8/site-packages/torchaudio/extension/extension.py", line 18, in _init_script_module
    torch.classes.load_library(path)
  File "/home/user01/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/_classes.py", line 46, in load_library
    torch.ops.load_library(path)
  File "/home/user01/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/home/user01/miniconda3/envs/myenv/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /nas/ei/home/user01/miniconda3/envs/myenv/lib/python3.8/site-packages/torchaudio/_torchaudio.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtERKSt10shared_ptrIS0_EPSo

```

Any help or suggestion regarding the installation step would be helpful. 

These are the specific versions I am using:

```
torch                     1.6.0                    pypi_0    pypi
torchaudio                0.8.1                      py38    pytorch
torchtext                 0.4.0                    pypi_0    pypi
torchvision               0.9.1                py38_cu102    pytorch
transformers              3.0.2                    pypi_0    pypi
spacy                     2.3.2                    pypi_0    pypi
numpy                     1.19.1                   pypi_0    pypi
en-core-web-sm            2.3.1                    pypi_0    pypi
rank-bm25                 0.2.1                    pypi_0    pypi
nltk                      3.5                      pypi_0    pypi
opennmt-py                1.2.0                    pypi_0    pypi
```

**Comment by roemmele** [comment]
Hi, I am really sorry for not responding to this sooner, I was failing to receive issue notifications. If you're still interested in this, can you try installing with a previous version of python? Looks like the demo instance is running Python 3.6 (I did "conda create -n env python=3.6"). I'm not sure why the dependency versions would be incompatible with python 3.8, but that would be my first step.

**Comment by mmcs-work** [comment]
Hi, Thanks for the answer. I guess python 3.6 was indeed the point. I created a colab environment with python3.6 and then installed the library. And everything worked. I didn't compare with different library versions in the python 3.6 environment and python 3.7 environments. But here is the package list from python 3.6. 

```
absl-py==0.13.0
answerquest @ git+https://github.com/roemmele/answerquest.git@85f4f61dce0e7bafe935aa99b7522d1834bee898
blis==0.4.1
cachetools==4.2.2
catalogue==1.0.0
certifi==2021.5.30
charset-normalizer==2.0.4
click==8.0.1
ConfigArgParse==1.5.2
cymem==2.0.5
dataclasses==0.8
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz
filelock==3.0.12
Flask==2.0.1
future==0.18.2
google-auth==1.35.0
google-auth-oauthlib==0.4.5
grpcio==1.39.0
idna==3.2
importlib-metadata==4.6.4
itsdangerous==2.0.1
Jinja2==3.0.1
joblib==1.0.1
Markdown==3.3.4
MarkupSafe==2.0.1
murmurhash==1.0.5
nltk==3.5
numpy==1.19.1
oauthlib==3.1.1
OpenNMT-py==1.2.0
packaging==21.0
plac==1.1.3
preshed==3.0.5
protobuf==3.17.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyonmttok==1.26.4
pyparsing==2.4.7
PyYAML==5.4.1
rank-bm25==0.2.1
regex==2021.8.21
requests==2.26.0
requests-oauthlib==1.3.0
rsa==4.7.2
sacremoses==0.0.45
sentencepiece==0.1.96
six==1.16.0
spacy==2.3.2
srsly==1.0.5
tensorboard==2.6.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
thinc==7.4.1
tokenizers==0.8.1rc1
torch==1.6.0
torchtext==0.4.0
tqdm==4.62.2
transformers==3.0.2
typing-extensions==3.10.0.0
urllib3==1.26.6
waitress==2.0.0
wasabi==0.8.2
Werkzeug==2.0.1
zipp==3.5.0
```

**Comment by roemmele** [comment]
Ok, I'm glad that worked. When I have a chance I will try to figure out what the issue with python 3.8 is. Thanks for letting me know and following up!
